package org.yschwartz.try_utils.exception;

public class ExceptionB extends RuntimeException {
}
